args.threshold-pred-score \n replacement_using BERT added
Sunkyoung/AttacKing-Sejong pull request #3
Opened 2021-06-04 06:38 UTC by didtngh97

In arg --threshold-pred-score is added 
after important score process is updated with 
replacement_using BERT method

2021-06-04 08:47 UTC, Sunkyoung requested changes
한 번 커밋하시는 것보다.. 변경 사항마다 (어렵다면 함수 단위라도..) 커밋 해주시면 보기에 훨씬 편리합니당.. :)

2021-06-04 08:47 UTC, Sunkyoung commented on utils/attack.py
> +    word_pred_scores_all, word_predictions = torch.topk(
torch.topk 에서 return 하는 것이 value랑 indices 여서 변수명을 가독성 좋게 변경했었습니다.
legacy 변수명 그대로 안따라가도 될 것 같아요!

2021-06-04 08:47 UTC, Sunkyoung commented on utils/attack.py
> +        word_pred_scores = word_pred_scores_all[top_index].unsqueeze(0)
important score는 CLS와 SEP 제외하고 진행해서 word_index_with_I_score 가 두 special token을 제외한 index들의 list인데 tgt_word 에 top_index + 1는 어떤 이유에서 해주는 걸까요?

2021-06-04 08:47 UTC, Sunkyoung commented on utils/attack.py
> +        word_pred_scores = word_pred_scores_all[top_index].unsqueeze(0)
그리고 아래의 word_predictions, word_pred_scores_all은 다르게 top_index으로 get 했는지 이유를 알 수 있을까요?

2021-06-04 08:47 UTC, Sunkyoung commented on utils/attack.py
> +            temp_label = torch.argmax(temp_prob)
label prediction 하는 다른 코드와 형식을 통일하면 좋을 것 같아요!

2021-06-04 08:47 UTC, Sunkyoung commented on utils/attack.py
> +            temp_label = torch.argmax(temp_prob)
이처럼 수정하는 편이 어떨까요?

```
input_tensor = processor.get_tensor(temp_replace).to('cuda')    

with torch.no_grad():       
    logit = finetuned_model(input_tensor)[0] 
temp_logit= logit.detach()  
temp_label = torch.argmax(pred_logit, dim=1).flatten()  

feature.query += 1
```

2021-06-04 08:53 UTC, didtngh97 commented on utils/attack.py
> +    word_pred_scores_all, word_predictions = torch.topk(
앗 그렇군요 이건 뭐 이렇게 하면 될 거 같습니다!

2021-06-04 08:59 UTC, didtngh97 commented on utils/attack.py
> +        word_pred_scores = word_pred_scores_all[top_index].unsqueeze(0)
아 넵 이부분에 대해서 설명해드리면 
feature 에 저장되어 있는 inputs_ids 에는 CLS 가 포함 되어 있고 
important score 에는 special token 이 없기 때문에 CLS 가 포함 되어 있지 않습니다 
따라서 important score의 index 는 0 이 첫 단어 가 되지만 
inputs_ids 에서는 CLS 가  첫 단어가 되므로 index top_index 에 1을 더해주어야 합니다 
또 아래의 word_predictions 와 word_pred_scores_all 은 special token 이 없으므로 top index 를 그대로 사용해주어도 됩니다!

2021-06-04 09:06 UTC, didtngh97 commented on utils/attack.py
> +            temp_label = torch.argmax(temp_prob)
오호 이렇게 할 수 있었군요 수정해서 commit 하겠습니다! temp prob 도 필요하기 때문에 그부분 추가하도록 하겠습니다!

2021-06-04 09:25 UTC, didtngh97 commented
label prediction form is unified 
word_predictions variable changed to word_pred_idx

2021-06-04 09:34 UTC, Sunkyoung commented on utils/attack.py
> +    word_pred_scores_all, word_predictions = torch.topk(
넵 index를 Idx로 줄여서 보통 많이 사용합니다!

2021-06-04 09:37 UTC, Sunkyoung commented on utils/attack.py
> +        word_pred_scores = word_pred_scores_all[top_index].unsqueeze(0)
그러면 이렇게 수정해서 통일하는 건 어떨까요? 
```
target_input = feature.input_ids[1:-1]
tgt_word = target_input [top_index]
```

2021-06-04 09:40 UTC, Sunkyoung commented on utils/attack.py
> +            temp_prob = torch.softmax(temp_logit, -1)
temp logit이 원래의 temp_prob와 같은 값이라 temp_prob을 추가 정의안해도 되지 않을까 싶습니다!

2021-06-04 09:58 UTC, didtngh97 commented on utils/attack.py
> +        word_pred_scores = word_pred_scores_all[top_index].unsqueeze(0)
그것도 좋은 방법입니다 
하지만 이후에 inference 를 진행할때는 앞 뒤에 CLS 와 SEP을 따로 추가 해주어야 합니다
통일하고 CLS 와 SEP을 추가하는 방향으로 수정해 볼까요?

2021-06-04 09:59 UTC, didtngh97 commented on utils/attack.py
> +            temp_prob = torch.softmax(temp_logit, -1)
아 logit 값이 softmax 되어진 값인가요?

2021-06-04 14:38 UTC, Sunkyoung commented on utils/attack.py
> +            temp_prob = torch.softmax(temp_logit, -1)
음 softmax 되기 전의 값은 맞는데, predicted label을 위해 사용되는 것이라면, 
`temp_label = torch.argmax(pred_logit, dim=1).flatten() `
이 부분에서 argmax 시에 dimension 1로 한 후 flatten 하기 때문에 따로 softmax를 사용하지 않아도 됩니다!

2021-06-04 15:16 UTC, didtngh97 commented on utils/attack.py
> +            temp_prob = torch.softmax(temp_logit, -1)
앗 넵 이후에 밑에서 softmax 된 값이 gap 계산에 쓰이기 때문에 추가했습니다!

2021-06-05 14:38 UTC, Sunkyoung approved these changes

2021-06-05 14:38 UTC, merged